name: "Prepare Release"
description: "Common setup for craft/prepare"
inputs:
  version:
    description: Version to release (optional)
    required: false
  calver:
    description: Use automatic CalVer versioning
    required: true
    default: false
  merge_target:
    description: Target branch to merge into. Uses the default branch as a fallback (optional)
    required: false
  force:
    description: Force a release even when there are release-blockers (optional)
    required: false
  craft_version:
    description: The craft version to use, defaults to "latest" (optional)
    required: false
  path:
    description: The path that Craft will run inside. Defaults to `.`
    required: true
    default: "."
  craft_config_from_merge_target:
    description: Use the craft config from the merge target branch. Defaults to the repository's default branch
    default: false

runs:
  using: "composite"
  steps:
    - id: killswitch
      name: Check release blockers
      shell: bash
      env:
        FORCE_INPUT: ${{ inputs.force }}
      run: |
        if [[ -z "$FORCE_INPUT" ]] && gh issue list -l release-blocker -s open | grep -q '^[0-9]\+[[:space:]]'; then
          echo "Open release-blocking issues found, cancelling release...";
          gh api -X POST repos/:owner/:repo/actions/runs/$GITHUB_RUN_ID/cancel;
        fi
    - name: Determine version
      shell: bash
      env:
        VERSION_INPUT: ${{ inputs.version }}
        CALVER_INPUT: ${{ inputs.calver }}
      run: |
        if [[ -n "$VERSION_INPUT" ]]; then
          echo "RELEASE_VERSION=$VERSION_INPUT" >> $GITHUB_ENV;
        elif [[ "$CALVER_INPUT" = 'true' ]]; then
          # Our releases are on 15th of each month so go back 14 days (a fortnight)
          DATE_PART=$(date -d '-1 fortnight' +'%y.%-m')
          declare -i PATCH_VERSION=0
          while gh api --silent "repos/:owner/:repo/git/ref/tags/$DATE_PART.$PATCH_VERSION" 2>/dev/null; do
            PATCH_VERSION+=1
          done
          echo "RELEASE_VERSION=${DATE_PART}.${PATCH_VERSION}" >> $GITHUB_ENV;
        else
          echo "You need to provide a version to release.";
          exit 1;
        fi
    - name: Set git user to getsentry-bot
      shell: bash
      run: |
        echo "GIT_COMMITTER_NAME=getsentry-bot" >> $GITHUB_ENV;
        echo "GIT_AUTHOR_NAME=getsentry-bot" >> $GITHUB_ENV;
        echo "EMAIL=bot@sentry.io" >> $GITHUB_ENV;
    - name: Install Craft
      shell: bash
      env:
          CRAFT_RELEASE: ${{ inputs.craft_version && inputs.craft_version != 'latest' && format('tags/{0}', inputs.craft_version) || 'latest' }}
      run: |
        
        craft_url=$(curl -s "https://api.github.com/repos/getsentry/craft/releases/$CRAFT_RELEASE" | jq -r '.assets[].browser_download_url | select(endswith("/craft"))')
        sudo curl -sL -o /usr/local/bin/craft "$craft_url"
        sudo chmod +x /usr/local/bin/craft
    - name: Checkout merge target branch
      if: inputs.craft_config_from_merge_target == 'true' && inputs.merge_target
      shell: bash
      env:
        MERGE_TARGET: ${{ inputs.merge_target }}
      run: |
        git fetch origin "$MERGE_TARGET"
        git checkout "$MERGE_TARGET"
    - name: Craft Prepare
      id: craft
      shell: bash
      env:
        CRAFT_LOG_LEVEL: Warn
      working-directory: ${{ inputs.path }}
      run: |
        # Ensure we have origin/HEAD set
        git remote set-head origin --auto
        CRAFT_LOG_LEVEL=Debug craft prepare "$RELEASE_VERSION"
    - name: Checkout merge target branch
      # We need to check out the merge target branch again because at the end of `craft prepare`
      # craft checks out the default branch
      if: inputs.craft_config_from_merge_target == 'true' && inputs.merge_target
      shell: bash
      env:
        MERGE_TARGET: ${{ inputs.merge_target }}
      run: |
        git checkout "$MERGE_TARGET"
    - name: Read Craft Targets
      id: craft-targets
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        CRAFT_LOG_LEVEL: Warn
      run: |
        targets=$(craft targets | jq -r '.[]|" - [ ] \(.)"')

        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        echo "targets<<EOF" >> "$GITHUB_OUTPUT"
        echo "$targets" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
    - name: Get Release Git Info
      id: release-git-info
      shell: bash
      env:
        CHECKOUT_REF: ${{ inputs.craft_config_from_merge_target == 'true' && inputs.merge_target && '@{-2}' || '@{-1}' }}
      run: |
        # craft switches back to `main` but we want info on the release branch
        # if we previously checked out the merge target branch (craft_config_from_merge_target)
        # we need to go back 2 checkouts, otherwise 1
        git checkout "$CHECKOUT_REF"
        echo "branch=$(git rev-parse --symbolic-full-name HEAD)" >> "$GITHUB_OUTPUT"
        echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        echo "last=$(git rev-parse --verify "$(git describe --tags --abbrev=0)" || echo HEAD)" >> "$GITHUB_OUTPUT"
    - name: Request publish
      shell: bash
      env:
        PATH_INPUT: ${{ inputs.path }}
        MERGE_TARGET_INPUT: ${{ inputs.merge_target }}
        RELEASE_LAST: ${{ steps.release-git-info.outputs.last }}
        RELEASE_BRANCH: ${{ steps.release-git-info.outputs.branch }}
        RELEASE_SHA: ${{ steps.release-git-info.outputs.sha }}
        CRAFT_TARGETS: ${{ steps.craft-targets.outputs.targets }}
      run: |
        if [[ "$PATH_INPUT" == '.' ]]; then
          subdirectory='';
        else
          subdirectory="/$PATH_INPUT";
        fi

        if [[ -n "$MERGE_TARGET_INPUT" ]]; then
          merge_target="$MERGE_TARGET_INPUT";
        else
          merge_target='(default)';
        fi

        title="publish: $GITHUB_REPOSITORY$subdirectory@$RELEASE_VERSION"

        # So, GitHub only allows search with the "in" operator and this
        # issue search can return non-exact matches. Due to this, we extract
        # the titles of the returned issues and check them with `grep -xw`
        # which does a non-regexp full-line match (exact match for us)
        if gh -R $GITHUB_REPOSITORY_OWNER/publish issue list -S "'$title' in:title" --json title -q '.[] | .title' | grep -qxF -- "$title"; then
          echo "There's already an open publish request, skipped issue creation.";
          exit 0;
        fi

        body="Requested by: @$GITHUB_ACTOR

        Merge target: $merge_target

        Quick links:
        - [View changes](https://github.com/$GITHUB_REPOSITORY/compare/$RELEASE_LAST...$RELEASE_BRANCH)
        - [View check runs](https://github.com/$GITHUB_REPOSITORY/commit/$RELEASE_SHA/checks/)

        Assign the **accepted** label to this issue to approve the release.
        To retract the release, the person requesting it must leave a comment containing \`#retract\` on a line by itself under this issue.

        ### Targets

        $CRAFT_TARGETS

        Targets marked with a checkbox have already been executed.  Administrators can manually tick a checkbox to force craft to skip it.
        "
        gh issue create -R "$GITHUB_REPOSITORY_OWNER/publish" --title "$title" --body "$body"
